Remove use of Met Office scripts

diff --git a/access-coupled b/access-coupled
--- a/access-coupled
+++ b/access-coupled
@@ -1,127 +1,58 @@
 #!/usr/bin/env bash
-# *****************************COPYRIGHT******************************
-# (C) Crown copyright Met Office. All rights reserved.
-# For further details please refer to the file COPYRIGHT.txt
-# which you should have received as part of this distribution.
-# *****************************COPYRIGHT******************************
-#-----------------------------------------------------------------------
-# Code Owner: Please refer to the UM file CodeOwners.txt
-# This file belongs in section: Rose scripts
-#-----------------------------------------------------------------------
-# NAME
-#     um-coupled
+
+# Driver script for ACCESS-CM2
+
+# Input environment variables
 #
-# SYNOPSIS
-#     um-coupled [EXE ...]
-#
-# DESCRIPTION
-#     Set up the environment and namelists for running the coupled model and
-#     passes an MPI command file to the um-atmos script.
-#
-# ARGUMENTS
-#     None.
-#
-# ENVIRONMENT VARIABLES
-#     This script uses the following variables:
-#
-#     ATMOS_EXEC
-#          The atmosphere executable to launch. If provided this must be the
-#          full path to the executable. Default=um-atmos.exe.
-#     ATMOS_LINK
-#          Name of the symbolic link to the atmosphere executable.
-#          Default=toyatm.
-#     ATMOS_COUPLE_TYPE
-#          Determine whether to couple through the master or all atmosphere
-#          processors. Default=M (master processor).
-#     CICE_ATMOS_DATA
-#          Directory for CICE atmosphere forcing data.
-#     CICE_GRID
-#          Full path to the CICE grid file.
-#     CICE_KMT
-#          Full path to the CICE kmt file.
-#     CICE_NL
-#          File containing the CICE input namelist. Default=ice_in.
-#     CICE_NPROC
-#          Number of processors for CICE in the ocean executable.
-#     CICE_OCEAN_DATA
-#          Directory for CICE ocean forcing data.
-#     CICE_RESTART
-#          File containing CICE restart data. Default=ice.restart_file.
-#     CICE_START
-#          Location of the CICE start dump.
+# Executable paths
+#     ATMOS_EXEC: The full path to the UM executable
+#     ICE_EXEC:   The full path to the CICE executable
+#     OCEAN_EXEC: The full path to the MOM executable
+
+# Directories
+#     ARCHIVE_DIR
+#     ATM_RUNDIR
+#     CPL_RUNDIR
+#     ICE_RUNDIR
+#     OCN_RUNDIR
+#     DATAM
+#          Directory for time-stamped STASH and dump files. Default=$DATAW.
+
+# Decomposition related
+#     UM_ATM_NPROCX:   Number of atmosphere processors east-west.
+#     UM_ATM_NPROCY:   Number of atmosphere processors north-south.
+#     FLUME_IOS_NPROC: Number of processors for the UM's I/O server.
+#     OMP_NUM_THREADS: Applies to UM only
+#     OCN_NPROCX
+#     OCN_NPROCY
+#     ICE_NPROCS
+
+# Other flags
+#     COUPLER
 #     CONTINUE
 #          Flag for Nrun - If not provided a new history file is created from INITHIS.
 #          Default=false.
-#     COUPLED_TASK_SPACING
-#          Spacing between tasks of different models, for load-balancing with
-#          OASIS3-MCT. Default=0.
-#     COUPLER
-#          Coupling method to use, currently OASIS3 or OASIS3-MCT.
-#     DATAM
-#          Directory for time-stamped STASH and dump files. Default=$DATAW.
-#     DATAW
-#          Location of task-shared working directory. Defaults:
-#          1. $ROSE_DATA
-#          2. $PWD
-#     FLUME_IOS_NPROC
-#          Number of processors for the UM's I/O server.
-#     HIST_DIR
-#          Directory containing an existing UM history file
-#          and (if appropriate) partial sums files. Default=$DATAM
-#     OASIS_EXEC
-#          The oasis executable to launch. If provided this must be the
-#          full path to the executable. Default=/projects/ocean/oasis/oasis3_3.0/20110919_para_MxSeg1500_nc362/prism/ibm_power7/bin/oasis3.MPI1.x
-#     OASIS_LINK
-#          Name of the symbolic link to the OASIS executable. Default=oasis3.
-#     OCEAN_EXEC
-#          The full path to the OASIS executable to launch.
+#     RUNID: Stem name of output files.
+#     WARM_RESTART_NRUN
+
+# Internal environment variables
+#     ATMOS_LINK
+#          Name of the symbolic link to the atmosphere executable
+#          (as set in OASIS namcouple).
+#     ICE_LINK
+#          Name of the symbolic link to the ice executable.
 #     OCEAN_LINK
-#          Name of the symbolic link to the ocean executable. Default=toyoce.
-#     MODELBASIS
-#          The basis time for the model run. If not provided, read from the
-#          UM namelists.
-#     NAMCOUPLE_DIR
-#          Directory containing the namcouple files for OASIS.
-#     NAMCOUPLE_STUB
-#          Stem name of namcouple files. Default=namcouple_.
-#     OCEAN_COUPLE_TYPE
-#          Determine whether to couple through the master or all ocean
-#          processors. Default=M (master processor).
-#     PRISM_NPROC
-#          Number of processors for the OASIS executable.
-#     RMP_DIR
-#          Directory containing the remapping weights files for OASIS.
-#     TASKEND
-#          End time for this model run. If not provided, the run length is
-#          calculated from the UM namelists.
-#     TASKSTART
-#          The start time for this model run.
-#     RUNID
-#          Stem name of output files. Default=atmos.
-#     UM_ATM_NPROCX
-#          Number of atmosphere processors east-west.
-#     UM_ATM_NPROCY
-#          Number of atmosphere processors north-south.
+#          Name of the symbolic link to the ocean executable.
+
+#     UM_NPES
+#     NPROC_MAX
+#     OCN_NPES
+#     TOT_NPES
 #-----------------------------------------------------------------------
 
 set -xeu
 
 echo "ACCESS COUPLED MODEL DRIVER", $PWD
-
-# Source common UM script functions from file
-um_scripts=$(dirname "$0")/um_script_functions
-if [ -f "$um_scripts" ] ; then
-    . $um_scripts
-else
-    echo "[FAIL] UM script functions file not found: $um_scripts " 1>&2
-    echo "[FAIL] Ensure the UM file above is located in the same " 1>&2
-    echo "[FAIL] directory as this script                        " 1>&2
-    exit 1
-fi
-
-usf_print_script_path
-
-export RUNID=${RUNID:-atmos}
 
 if [[ -z ${COUPLER:-} ]]; then
     echo "[FAIL] Coupler (COUPLER=<model>) not defined in the environment." >&2
@@ -144,10 +75,6 @@ ln -sf $ICE_EXEC $ICE_LINK
 # Redefine exec names for the setup scripts later:
 ATMOS_EXEC=$ATMOS_LINK
 OCEAN_EXEC=$OCEAN_LINK
-
-# Print exec paths to file
-usf_which $ATMOS_EXEC
-usf_which $OCEAN_EXEC
 
 export UM_NPES=$((UM_ATM_NPROCX * UM_ATM_NPROCY))
 NPROC_MAX=$((UM_NPES + FLUME_IOS_NPROC))
@@ -175,7 +102,7 @@ fi
 
 # ########################################################################
 # ### OASIS
-  # ########################################################################
+# ########################################################################
 
 fix_namcouple.py $CPL_RUNDIR/namcouple
 if [[ $? != 0 ]]; then
@@ -188,8 +115,6 @@ if [[ $? != 0 ]]; then
   echo "Error from fix_diag_table"
   exit 1
 fi
-
-export OMPI_MCA_hwloc_base_mem_alloc_policy=local_only
 
 mkdir -p $OCN_RUNDIR/RESTART $OCN_RUNDIR/HISTORY
 mkdir -p $ICE_RUNDIR/RESTART $ICE_RUNDIR/HISTORY
@@ -249,4 +174,101 @@ export ACCESSRUNCMD="${TOT_DEBUG:-}--rankfile $CYLC_TASK_WORK_DIR/rankfile \
 
 echo "RUNCOMMAND", $ACCESSRUNCMD
 
-access-atmos
+# UM specific setup
+
+cd ${ATM_RUNDIR}
+
+if [[ -z ${VN:-} ]]; then
+  echo "[FAIL] UM version (VN=x.y) not defined in the environment." >&2
+  exit 10
+fi
+if [[ ! $VN =~ ^([0-9])+\.([0-9])+$ ]]; then
+  echo "[FAIL] UM version \$VN=\"$VN\" not of the form (VN=x.y)."
+  exit 20
+fi
+
+export DR_HOOK=${DR_HOOK:-0}
+export DR_HOOK_OPT=${DR_HOOK_OPT:-noself}
+export PRINT_STATUS=${PRINT_STATUS:-PrStatus_Normal}
+export UM_THREAD_LEVEL=${UM_THREAD_LEVEL:-MULTIPLE}
+
+# Create new or use existing history file
+export HISTORY=${HISTORY:-atmos.xhist}
+if [[ ${CONTINUE:-false} == "false" ]] ; then
+  rm -f $HISTORY
+else
+  if [[ ! -r $HISTORY ]]; then
+    echo "[FAIL] Cannot read history file $HISTORY" >&2
+    exit 30
+  fi
+fi
+export HISTORY_TEMP=thist
+
+# Processor variables
+export UM_NPES=$((UM_ATM_NPROCX * UM_ATM_NPROCY))
+export NPROC=$((UM_NPES + FLUME_IOS_NPROC))
+export HOUSEKEEP=hkfile
+export STASHC=STASHC
+export ATMOSCNTL=ATMOSCNTL
+export SHARED_NLIST=${SHARED_FNAME:-SHARED}
+export ERROR_FLAG=errflag
+export STASHMASTER=${STASHMSTR:-$UMDIR/vn$VN/ctldata/STASHmaster}
+export IDEALISE=IDEALISE
+export IOSCNTL=IOSCNTL
+
+export STDOUT_FILE=${ATMOS_STDOUT_FILE:-pe_output/atmos.fort6.pe}
+mkdir -p $(dirname $STDOUT_FILE)
+# Delete any previous .pe* files:
+rm -f $STDOUT_FILE*
+
+# Since we need to process some data after the executable we can trap the EXIT
+# signal to do this automatically whenever this script exits.  This also
+# catches times when this script is killed for any reason.
+SIGNALS='EXIT'
+FINALLY() {
+  for S in $SIGNALS; do
+    trap '' $S # Switch off traps
+  done
+
+  PE0_SUFFIX=$(echo $((NPROC - 1)) | sed s/./0/g)
+  UM_PE0_STDOUT_FILE="${STDOUT_FILE}${PE0_SUFFIX}"
+  if [[ -s "$UM_PE0_STDOUT_FILE" ]]; then
+    echo '%PE0 OUTPUT%'
+    cat "$UM_PE0_STDOUT_FILE"
+  elif [[ -f "$UM_PE0_STDOUT_FILE" ]]; then
+    echo "PE0 file exists, but has zero size"
+  else
+    echo "Could not find PE0 output file: $UM_PE0_STDOUT_FILE"
+  fi
+
+  # Remove output from other PEs unless requested otherwise
+  if [[ ${ATMOS_KEEP_MPP_STDOUT:-false} == "false" ]] ; then
+    for file in ${STDOUT_FILE}* ; do
+      if [[ $file != "$UM_PE0_STDOUT_FILE" ]]; then
+        rm $file
+      fi
+    done
+  fi
+
+  if [[ -f "$UM_PE0_STDOUT_FILE" ]]; then
+    # rose-ana expects fixed filenames so we link to .pe0 as otherwise the
+    # filename depends on the processor decomposition
+    if [[ $UM_PE0_STDOUT_FILE != ${STDOUT_FILE}0 ]]; then
+      ln -sf $(basename $STDOUT_FILE)$PE0_SUFFIX ${STDOUT_FILE}0
+    fi
+  fi
+}
+
+for S in $SIGNALS; do
+  trap 'FINALLY' $S
+done
+
+# rose mpi-launch -v $COMMAND
+
+# ACCESSRUNCMD not compatible with rose mpi-launch at the moment.
+# Using --mca rmaps_base_mapping_policy '' causes problems with totalview so set as
+# environment variable instead
+# /apps/openmpi/wrapper/mpirun --mca rmaps_base_mapping_policy '' ${ACCESSRUNCMD}
+export OMPI_MCA_hwloc_base_mem_alloc_policy=local_only
+export OMPI_MCA_rmaps_base_mapping_policy=''
+mpirun ${ACCESSRUNCMD}
